USE [master]
GO

/****** Object:  Database [OneHub_Admin]    Script Date: 12-Apr-17 2:49:34 PM ******/
CREATE DATABASE [OneHub_Admin]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'App', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQL16\MSSQL\DATA\Admin.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'App_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQL16\MSSQL\DATA\Admin_log.ldf' , SIZE = 5696KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [OneHub_Admin] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OneHub_Admin].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OneHub_Admin] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OneHub_Admin] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OneHub_Admin] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OneHub_Admin] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OneHub_Admin] SET ARITHABORT OFF 
GO

ALTER DATABASE [OneHub_Admin] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OneHub_Admin] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OneHub_Admin] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OneHub_Admin] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OneHub_Admin] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OneHub_Admin] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OneHub_Admin] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OneHub_Admin] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OneHub_Admin] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OneHub_Admin] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OneHub_Admin] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OneHub_Admin] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OneHub_Admin] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OneHub_Admin] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OneHub_Admin] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OneHub_Admin] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OneHub_Admin] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OneHub_Admin] SET RECOVERY FULL 
GO

ALTER DATABASE [OneHub_Admin] SET  MULTI_USER 
GO

ALTER DATABASE [OneHub_Admin] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OneHub_Admin] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OneHub_Admin] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OneHub_Admin] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [OneHub_Admin] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OneHub_Admin] SET QUERY_STORE = OFF
GO

USE [OneHub_Admin]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [OneHub_Admin] SET  READ_WRITE 
GO


