CREATE TABLE [dbo].[IncomingLetter] (
    [Id]                 UNIQUEIDENTIFIER NOT NULL,
    [CreatedBy]          VARCHAR (256)    NOT NULL,
    [CreationDate]       DATETIME2 (7)    NOT NULL,
    [LastModified]       DATETIME2 (7)    NOT NULL,
    [IsDeleted]          BIT              CONSTRAINT [DF_IncomingLetters_IsDeleted] DEFAULT ((0)) NULL,
    [Language]           INT              CONSTRAINT [DF_IncomingLetters_Language] DEFAULT ((1)) NULL,
    [EntityId]           UNIQUEIDENTIFIER NOT NULL,
    [Subject]            NVARCHAR (4000)  NOT NULL,
    [CorrespondenceFrom] UNIQUEIDENTIFIER NOT NULL,
    [CorrespondenceTo]   UNIQUEIDENTIFIER NULL,
    [IncomingNumber]     NVARCHAR (256)   NULL,
    [IncomingDate]       DATETIME2 (7)    NULL,
    [OutgoingNumber]     NVARCHAR (256)   NULL,
    [OutgoingDate]       DATETIME2 (7)    NULL,
    [Confidential]       BIT              NULL,
    [CorrespondentName]  NVARCHAR (1024)  NULL,
    [RegisteringDate]    DATETIME2 (7)    NOT NULL,
    [RegisteredBy]       VARCHAR (256)    NOT NULL,
    [IndexingDate]       DATETIME2 (7)    NULL,
    [IndexedBy]          VARCHAR (256)    NULL,
    [ScanningDate]       DATETIME2 (7)    NULL,
    [ScannedBy]          VARCHAR (256)    NULL,
    [SendingDate]        DATETIME2 (7)    NULL,
    [SentBy]             VARCHAR (256)    NULL,
    [FK_ReplyTo]         UNIQUEIDENTIFIER NULL,
    [FK_Document]        UNIQUEIDENTIFIER NULL,
    [Status]             INT              CONSTRAINT [DF_IncomingLetters_Status] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_IncomingLetters] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_IncomingLetters_Documents] FOREIGN KEY ([FK_Document]) REFERENCES [dbo].[Document] ([Id])
);

