CREATE TABLE [dbo].[OutgoingLetter] (
    [Id]                       UNIQUEIDENTIFIER NOT NULL,
    [CreatedBy]                VARCHAR (8000)   NOT NULL,
    [CreationDate]             DATETIME2 (7)    NOT NULL,
    [LastModified]             DATETIME2 (7)    NOT NULL,
    [IsDeleted]                BIT              NULL,
    [Language]                 INT              NULL,
    [EntityId]                 UNIQUEIDENTIFIER NOT NULL,
    [Subject]                  VARCHAR (8000)   NOT NULL,
    [From]                     VARCHAR (8000)   NOT NULL,
    [To]                       VARCHAR (8000)   NOT NULL,
    [IncomingNumber]           VARCHAR (8000)   NULL,
    [IncomingDate]             DATETIME2 (7)    NULL,
    [OutgoingNumber]           VARCHAR (8000)   NULL,
    [OutgoingDate]             DATETIME2 (7)    NULL,
    [Confidential]             BIT              NULL,
    [ReviewingDate]            DATETIME2 (7)    NOT NULL,
    [ReviewedBy]               VARCHAR (8000)   NOT NULL,
    [MovingDate]               DATETIME2 (7)    NULL,
    [MovedBy]                  VARCHAR (8000)   NULL,
    [DeliveryDate]             DATETIME2 (7)    NULL,
    [DeliverdTo]               VARCHAR (8000)   NULL,
    [DeliveryConfirmationDate] DATETIME2 (7)    NULL,
    [FK_ReplyTo]               UNIQUEIDENTIFIER NOT NULL,
    [FK_Document]              UNIQUEIDENTIFIER NOT NULL,
    [FK_DraftLetter]           UNIQUEIDENTIFIER NOT NULL,
    [Status]                   INT              CONSTRAINT [DF_OutgoingLetters_Status] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_OutgoingLetters] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_OutgoingLetters_DraftLetters_1] FOREIGN KEY ([FK_DraftLetter]) REFERENCES [dbo].[DraftLetter] ([Id])
);

