//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 16/10/2016 07:46:00 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace OneHub.NET.TimeManagement
{

    /// <summary>
    /// There are no comments for OneHub.NET.TimeManagement.Task, OneHub.NET.TimeManagement in the schema.
    /// </summary>
    [Serializable()]
    [DataContract(IsReference = true)]
    public partial class Task : PlannedItem {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Task constructor in the schema.
        /// </summary>
        public Task()
        {
            this.Children = new List<Task>();
            this.Attachments = new List<TaskAttachment>();
            this.Assignments = new List<TaskAssignment>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for ReferenceNumber in the schema.
        /// </summary>
        [DataMember(Order=1)]
        public virtual string ReferenceNumber
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for SignedPDF in the schema.
        /// </summary>
        [DataMember(Order=2)]
        public virtual byte[] SignedPDF
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CommentThreadId in the schema.
        /// </summary>
        [DataMember(Order=3)]
        public virtual System.Nullable<System.Guid> CommentThreadId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PercentComplete in the schema.
        /// </summary>
        [DataMember(Order=4)]
        public virtual decimal PercentComplete
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ExpectedEndDate in the schema.
        /// </summary>
        [DataMember(Order=5)]
        public virtual System.DateTime ExpectedEndDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Project in the schema.
        /// </summary>
        public virtual Project Project
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Children in the schema.
        /// </summary>
        [DataMember(Order=6, EmitDefaultValue=false)]
        public virtual IList<Task> Children
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Parent in the schema.
        /// </summary>
        public virtual Task Parent
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Attachments in the schema.
        /// </summary>
        [DataMember(Order=7, EmitDefaultValue=false)]
        public virtual IList<TaskAttachment> Attachments
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Assignments in the schema.
        /// </summary>
        [DataMember(Order=8, EmitDefaultValue=false)]
        public virtual IList<TaskAssignment> Assignments
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Priority in the schema.
        /// </summary>
        [DataMember(Order=9, EmitDefaultValue=false)]
        public virtual Priority Priority
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Severity in the schema.
        /// </summary>
        [DataMember(Order=10, EmitDefaultValue=false)]
        public virtual Severity Severity
        {
            get;
            set;
        }
    }

}
