//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 16/10/2016 07:46:00 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace OneHub.NET.TimeManagement
{

    /// <summary>
    /// There are no comments for OneHub.NET.TimeManagement.Issue, OneHub.NET.TimeManagement in the schema.
    /// </summary>
    [Serializable()]
    [DataContract(IsReference = true)]
    public partial class Issue : IEntity {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Issue constructor in the schema.
        /// </summary>
        public Issue()
        {
            this.Type = 1;
            this.IsDeleted = false;
            this.Issues_FK_RelatedToIssue = new List<Issue>();
            this.IssueAttachments = new List<IssueAttachment>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [DataMember(Order=1)]
        public virtual System.Guid Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ReferenceNumber in the schema.
        /// </summary>
        [DataMember(Order=2)]
        public virtual string ReferenceNumber
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        [DataMember(Order=3)]
        public virtual string Name
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Description in the schema.
        /// </summary>
        [DataMember(Order=4)]
        public virtual string Description
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for RaisedBy in the schema.
        /// </summary>
        [DataMember(Order=5)]
        public virtual string RaisedBy
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Type in the schema.
        /// </summary>
        [DataMember(Order=6)]
        public virtual byte Type
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for RaisedDate in the schema.
        /// </summary>
        [DataMember(Order=7)]
        public virtual System.Nullable<System.DateTime> RaisedDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for SolutionDate in the schema.
        /// </summary>
        [DataMember(Order=8)]
        public virtual System.Nullable<System.DateTime> SolutionDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Resolution in the schema.
        /// </summary>
        [DataMember(Order=9)]
        public virtual string Resolution
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CommentThreadId in the schema.
        /// </summary>
        [DataMember(Order=10)]
        public virtual System.Nullable<System.Guid> CommentThreadId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IsDeleted in the schema.
        /// </summary>
        [DataMember(Order=11)]
        public virtual bool IsDeleted
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CreationDate in the schema.
        /// </summary>
        [DataMember(Order=12)]
        public virtual System.DateTime CreationDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for LastUpdateDate in the schema.
        /// </summary>
        [DataMember(Order=13)]
        public virtual System.Nullable<System.DateTime> LastUpdateDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CreatedBy in the schema.
        /// </summary>
        [DataMember(Order=14)]
        public virtual string CreatedBy
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for LastUpdatedBy in the schema.
        /// </summary>
        [DataMember(Order=15)]
        public virtual string LastUpdatedBy
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Issues_FK_RelatedToIssue in the schema.
        /// </summary>
        [DataMember(Order=16, EmitDefaultValue=false)]
        public virtual IList<Issue> Issues_FK_RelatedToIssue
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Issue_FK_RelatedToIssue in the schema.
        /// </summary>
        public virtual Issue Issue_FK_RelatedToIssue
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Severity in the schema.
        /// </summary>
        [DataMember(Order=17, EmitDefaultValue=false)]
        public virtual Severity Severity
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Priority in the schema.
        /// </summary>
        [DataMember(Order=18, EmitDefaultValue=false)]
        public virtual Priority Priority
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IssueAttachments in the schema.
        /// </summary>
        [DataMember(Order=19, EmitDefaultValue=false)]
        public virtual IList<IssueAttachment> IssueAttachments
        {
            get;
            set;
        }
    }

}
